### ISSUE TITLE
Не работает поиск по числовым запросам

### ISSUE THREAD

**Issue by borovoff** [himiklab/yii2-search-component-v2#13]
Поиск работает по всем запросам, в том числе содержащим цифры, но не работает с запросами, которые содержат только цифры.

Проблема с этой компонентой, поиском в целом или моим кодом?

**Comment by himiklab** [comment]
Попробуйте использовать ``Search::$parseNumeric = true``.

**Comment by borovoff** [comment]
Спасибо! 

Еще тогда разобрался, все работает. 😎
