### ISSUE TITLE
Использование параметра $fields в функции find

### ISSUE THREAD

**Issue by froZZen-gm** [himiklab/yii2-search-component-v2#16]
Здравствуйте!
Помогите, пожалуйста, разобраться с сабжевой возможностью.
В модели перепробовал все типы индекса для поля, которым собираюсь "фильтровать" запрос. Не работает... 
Без параметра $fields результаты есть, ставлю ['field' => 'value'] - нет результатов. Хотя, должны быть.
Спасибо.
С уважением

**Comment by froZZen-gm** [comment]
Должен сделать дополнение: 
если в поиске **одно слово**, то **работает**, если **словосочетание**, то **нет**

**Comment by zodiac163** [comment]
Проблема в реализации метода find. Если в метод передается массив fields, то строка поиска ($term) добавляется как new IndexTerm. В таком случае она не бьется на отдельные слова, а используется "как есть", то есть словосочетанием. А в индексированных данных каждое слово хранится отдельно. При таком подходе происходит сравнение словосочетания со словом, поэтому получается пустой результат поиска. 

Можно переопределить метод и добавлять 1й аргумент через QueryParser::parse($term), а весь запрос обернуть в Query\Boolean

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-search-component-v2/commit/18c181bd8ecd65087f9ea39333aec69e51784569
