### ISSUE TITLE
Не устанавливается

### ISSUE THREAD

**Issue by QuinLena15** [himiklab/yii2-search-component-v2#3]
Не получается установить. Пишет: Your requirements could not be resolved to an installable set of packages.

**Comment by himiklab** [comment]
Покажите весь вывод с консоли, пожалуйста.

**Comment by QuinLena15** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/10464561/7909918/df2116ec-0858-11e5-9306-09a143f0b1e2.png)

**Comment by himiklab** [comment]
Добавьте в свой `composer.json` строку `"zendframework/zendsearch": "2.0.0rc5"`

**Comment by QuinLena15** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/10464561/7910125/7a2549be-085a-11e5-8e57-f984a5d09109.png)

**Comment by himiklab** [comment]
Понятно, это ошибки в репозитории Zend.
Попробуйте `""zendframework/zendsearch": "dev-master"` должно пройти.

**Comment by QuinLena15** [comment]
Спасибо, получилось!

**Comment by himiklab** [comment]
Отлично. :)
