### ISSUE TITLE
Как пользоваться?

### ISSUE THREAD

**Issue by QuinLena15** [himiklab/yii2-search-component-v2#4]
Извините, не нашла как тут можно в личку написать. 
Не поняла, как использовать теперь расширение?)

**Comment by himiklab** [comment]
Тут нет лички.
Покажите модель которую хотите индексировать.

**Comment by QuinLena15** [comment]
<?php

namespace common\models;

use Yii;
use yii\data\ActiveDataProvider;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;
use himiklab\yii2\search\behaviors\SearchBehavior;

class Posts extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
	public $file;
	public $avatar;
	public $filename;
	public $name;
	public $canvas;
	public $rating;
	public $url;
	const STATUS_PUBLISH = 'publish';
	const STATUS_ARCHIVE = 'archive';
    public static function tableName()
    {
        return 'tbl_posts';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
			[['title', 'content','detail_picture','preview_picture', 'status','canvas','rating'], 'safe'],
            [['preview_picture','detail_picture','content', 'anons','comment_status'], 'string'],
            [['author_id', 'category_id',  'like_post', 'dislike_post','see_count'], 'integer'],
			[['like_post','dislike_post'], 'default','value'=>0],
            [['datetime','file', 'avatar', 'filename', 'name'], 'safe'],
			[['file'], 'file', 'extensions' => ['mp4']],
			
            [['title', 'status'], 'string', 'max' => 125]
        ];
    }
	

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Заголовок',
            'content' => '',
			'file'=>'Видео',
			'comment_status'=>'Разрешено комментирование',
            'anons' => 'Анонс',
            'author_id' => 'Автор записи',
            'category_id' => 'Категория',
            'preview_picture' => 'Картинка для анонса',
			'detail_picture' => 'Картинка для детального просмотра',
            'status' => 'Статус',
            'like_post' => 'Количество лайков',
            'dislike_post' => 'Количество дислайков',
            'datetime' => 'Дата',
			'categoryName' => 'Категория',
			'authorName' =>'Автор',
			'datePost' =>'Дата'
        ];
    }
		function getPublishedPosts($cat='')
		{
			return new ActiveDataProvider([
				'query' => Posts::find()
					->where(['status' => 'publish','category_id'=>$cat])
					->orderby(['datetime'=>SORT_DESC])
			]);
		}
		function getArchivePosts($cat='')
		{
			$cats = (empty($cat))?['status' => Posts::STATUS_ARCHIVE]:['status' => Posts::STATUS_ARCHIVE,'category_id'=>$cat];
			$res= new ActiveDataProvider([
				'query' => Posts::find()
					->where($cats)
					->orderby(['datetime'=>SORT_DESC]),
					'pagination' => ['pageSizeLimit' => [0,8]],
					
			]);
			
			return $res;
		}		
		
		public function urlp(){
		
			return '/news/index';
		}
		
		public function getRating(){
			$this->rating = $this->like_post - $this->dislike_post;
			return $this->rating;
		}
		
		public function getPostAnons(){
			if(empty($this->anons))
				$result = substr($this->content, 0, 300); 
			else
				$result = $this->anons;
			return $result;
		}
		
		public function getPictureAnons(){
			if(empty($this->preview_picture))
				$result = $this->detail_picture; 
			else
				$result = $this->preview_picture;
			return $result;
		}
		
		    public function getPublishedComments()
    {
        return new ActiveDataProvider([
            'query' => $this->getComments()
                ->where(['publish_status' => Comment::STATUS_PUBLISH])
        ]);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(User::className(), ['id' => 'author_id'])->
           from(User::tableName() . ' AS author');
    }
	
	
	
	    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id'])->
           from(Category::tableName() . ' AS category');
    }
	/* Геттер для названия категории */
	public function getCategoryName() {
		return $this->category->title;
	}
	/* Геттер для имени пользователя */
	public function getAuthorName() {
		return $this->author->username;
	}
	    public function getComments()
    {
        return $this->hasMany(Comment::className(), ['post_id' => 'id']);
    }
	public function getDatePost() {
		$date = date('d.m.Y',strtotime($this->datetime));
		return $date;
	}
	 public function getVideoFile() 
    {
		if(!is_dir(Yii::$app->params['uploadPath']. Yii::$app->user->id.'/'))
			mkdir(Yii::$app->params['uploadPath']. Yii::$app->user->id, 0755);
        return isset($this->avatar) ? Yii::$app->params['uploadPath']. Yii::$app->user->id.'/'.$this->avatar : null;
    }
	
	public function setArchive()
	{
		$this->status = Posts::STATUS_ARCHIVE;
		return $this->save();
	}

	
	
	
	public function uploadVideo() {

        $image = UploadedFile::getInstance($this, 'file');

        if (empty($image)) {
            return false;
        }

        $this->filename = $image->name;
        $ext = end((explode(".", $image->name)));
 
        $this->avatar = Yii::$app->security->generateRandomString().".{$ext}";

        return $image;
    }
}

**Comment by himiklab** [comment]
Как-то так:
В модель добавьте 
````php
public function behaviors()
{
    return [
        'search' => [
            'class' => SearchBehavior::className(),
            'searchFields' => function ($model) {
                /** @var self $model */
                return [
                    ['name' => 'title', 'value' => $model->title],
                    ['name' => 'body', 'value' => strip_tags($model->content)],
                    ['name' => 'url', 'value' => $model->url, 'type' => SearchBehavior::FIELD_KEYWORD],
                ];
            }
        ],
    ];
}
````
Хотя на счёт url не понятно откуда он у Вас берётся.

В конфигурацию приложения в секцию `components`:
````php
  'search' => [
      'class' => 'himiklab\yii2\search\Search',
      'models' => [
          'common\models\Posts',
      ],
],
````

И добавьте в свой проект мой модуль из папки `module`.

**Comment by QuinLena15** [comment]
url - это страница просмотра записи?
И по какой ссылке мне допустим результаты смотреть?

**Comment by himiklab** [comment]
Да.

Вы с Yii2 как давно знакомы? Возьмите лучше `yii2-app-basic`.

**Comment by QuinLena15** [comment]
С yii2 знакома недавно. 
Создала в папке frontend папку modules и скопировала туда из папки module.
В конфиге подключила:
'modules'=>[
        'search' => [
            'class' => 'frontend\modules\search\Search',
        ],
    ], 
В components:
'search' => [
			'class' => 'himiklab\yii2\search\Search',
			'models' => [
				'common\models\Posts',
			],
		],
Захожу по адресу /search/default/index?q=текст - The "текст" isn't found!
Хотя в базе есть запись с данным текстом. Я не так что-то подключаю? Подскажите, пожалуйста.

**Comment by himiklab** [comment]
А Вы данные свои проиндексировали? Кэш Lucene создался?

**Comment by QuinLena15** [comment]
Да, запустила. Вот что создалось в папке runtime.
![screenshot_1](https://cloud.githubusercontent.com/assets/10464561/8397517/130544e0-1dd7-11e5-8016-5d706a2f68cd.png)

**Comment by himiklab** [comment]
Покажите ту часть кода где подключается `SearchBehavior`.

**Comment by QuinLena15** [comment]
Это имеете ввиду?
public function behaviors()
{
    return [
        'search' => [
            'class' => SearchBehavior::className(),
            'searchScope' => function ($model) {
                /** @var \yii\db\ActiveQuery $model */
                $model->select(['title', 'content','id']);
                $model->andWhere(['indexed' => true]);
            },
            'searchFields' => function ($model) {
                /** @var self $model */
                return [
                    ['name' => 'title', 'value' => $model->title],
                    ['name' => 'body', 'value' => strip_tags($model->content)],
                    ['name' => 'url', 'value' => '/news/view/'.$model->id, 'type' => SearchBehavior::FIELD_KEYWORD],
                    // ['name' => 'model', 'value' => 'page', 'type' => SearchBehavior::FIELD_UNSTORED],
                ];
            }
        ],
    ];
}

**Comment by himiklab** [comment]
Вы должны этот код подогнать под свою модель, `$model->andWhere(['indexed' => true]);` Вам по моему вообще не нужно, или Вы добавили поле `indexed`? Просто попробуйте разобраться в коде компонента и модуля, если что-то не ясно, спрашивайте.

**Comment by QuinLena15** [comment]
Да, поле создала. Тип tinyint. И убирала, все равно мне не помогло. Постараюсь в коде еще посмотреть.

**Comment by himiklab** [comment]
Уберите вообще часть `searchScope`. В `$model->content` у Вас содержится искомый текст?
Попробуйте поискать что-то на английском, может дело в кодировке.
