### ISSUE TITLE
Can't install, composer fails

### ISSUE THREAD

**Issue by sjaakp** [himiklab/yii2-search-component-v2#5]
Composer fails in installing with the following error:

  Problem 1
    - himiklab/yii2-search-component-v2 2.0.1 requires zendframework/zendsearch * -> no matching package found.
    - himiklab/yii2-search-component-v2 2.0.0 requires zendframework/zendsearch * -> no matching package found.
    - Installation request for himiklab/yii2-search-component-v2 * -> satisfiable by himiklab/yii2-search-component-v2[2.0.0, 2.0.1].

**Comment by himiklab** [comment]
Add to your `composer.json`:
`"zendframework/zendsearch": "2.0.0rc5"`
and
`"zendframework/zend-stdlib:": "2.0.0rc5"`

**Comment by sjaakp** [comment]
Thanks. But it seems that zend-stdlib is no longer available in v. 2.0.0rc5. If I install a later version, zendsearch is still complaining it can’t find the right stdlib... *sigh*

 

  _____  

Sjaak Priester

sjaak@sjaakpriester.nl

 

Van: Dmitrii Bondarenko [mailto:notifications@github.com] 
Verzonden: donderdag 18 juni 2015 13:24
Aan: himiklab/yii2-search-component-v2
CC: Sjaak Priester
Onderwerp: Re: [yii2-search-component-v2] Can't install, composer fails (#5)

 

Add to your composer.json:
"zendframework/zendsearch": "2.0.0rc5"
and
"zendframework/zend-stdlib:": "2.0.0rc5"

**Comment by almix** [comment]
I add:
"zendframework/zendsearch": "2.0.0rc5",
		"zendframework/zend-stdlib": "2.3.1 as 2.0.0rc5",
		"himiklab/yii2-search-component-v2": "*"

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-search-component-v2/commit/ca2867dd577c035a840b4bd1e107b41a10476b23
