### ISSUE TITLE
Compatibility with PHP 7

### ISSUE THREAD

**Issue by sjaakp** [himiklab/yii2-search-component-v2#7]
Line 192 in Search.php gives a fatal error under PHP 7: Access to undeclared static property: ZendSearch\Lucene\Document\Field::$field

It reads:

```php
$document->addField(Field::$field['type'](
        $field['name'],
        $field['value']
));
```

The issue is resolved by changing it to:

```php
$document->addField(call_user_func(['\ZendSearch\Lucene\Document\Field', $field['type']],
        $field['name'],
        $field['value']
));
```

**Comment by himiklab** [comment]
Thanks!
https://github.com/himiklab/yii2-search-component-v2/commit/9a053fbef5d0e2a5b72c6a88966c826f394599db
