### ISSUE TITLE
Поиск по тексту и цифрам

### ISSUE THREAD

**Issue by krupni** [himiklab/yii2-search-component-v2#9]
Использовал данное расширение для создания каталога автозапчастей. Необходим был поиск по следующим полям: артикул, марка, модель, название запчасти. И возникла проблема с поиском именно по числам т.к. он отказывался искать по артикулу или по модели авто (которое состоит из цифр).  

В итоге проблема оказалась в методе `init()` в строке `Analyzer::setDefault(new CaseInsensitive());`

Использовал вместо: `ZendSearch\Lucene\Analysis\Analyzer\Common\Utf8\CaseInsensitive`
класс `ZendSearch\Lucene\Analysis\Analyzer\Common\Utf8Num\CaseInsensitive` и всё стало работать отлично. 

Возможно разработчик так и хотел сделать, но добавлю это тут может пригодится кому-нибудь.

**Comment by himiklab** [comment]
Спасибо!
https://github.com/himiklab/yii2-search-component-v2/commit/12cc30e10cf8dc3c458ee46afe9f59d992cc10bc
